name: Deploy Documentation

on:
  push:
  pull_request:

permissions:
  contents: write
  statuses: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
    	python -m pip install --upgrade pip setuptools wheel
    	pip install -r requirements.txt
	pip install ghp-import

    - name: Build MkDocs site
      run: mkdocs build

    - name: Deploy to GitHub Pages
      run: |
        mkdocs gh-deploy --force

      env:
       GITHUB_TOKEN: ${{ secrets.GH_PAT }}
